version: '3.3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    command: yarn start
    volumes:
      - .:/usr/app
  db:
    image: mysql:5.7
    container_name: 'mysql'
    command: --default-authentication-plugin=mysql_native_password 
    restart: always
    environment:
      - MYSQL_DATABASE=financas
      - MYSQL_ROOT_PASSWORD=93062435vss
      - MYSQL_PASSWORD=93062435vss
      - DB_HOSTNAME=mysql
      - TZ=America/Sao_Paulo
